# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudapp', '0002_auto_20160812_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('rut', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=12)),
                ('fono', models.CharField(max_length=12)),
                ('ofrece_servicio', models.BooleanField(default=False)),
                ('cantidad_reportes', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudapp.Comuna')),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='evento',
            name='pagina_facebook',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='pagina_web',
            field=models.CharField(max_length=100),
        ),
    ]
