# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudapp', '0004_auto_20160812_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='categoria',
            field=models.ManyToManyField(to='kudapp.Categoria'),
        ),
    ]
